name: Setup
description: Setup Node.js, cache and install dependencies
inputs:
  node-version:
    description: Node.js version
    required: false
    default: '14'
runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - uses: actions/cache@v2
      id: npm-cache
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci
      env:
        HUSKY_SKIP_INSTALL: 'true'
